### ISSUE TITLE
Use the non-minified versions if not in production environment

### ISSUE THREAD

**Issue by d-oliveros** [regou/angular-bsfy#4]
Is it possible to use the non-minified version when not in the production environment?Maybe by detecting the presence of process.env.NODE_ENV and using the non-minified libraries if NODE_ENV !== 'production'. I'm using [envify](https://github.com/hughsk/envify) btw.

**Comment by regou** [comment]
I don't think this is possible to change it without affecting other user's compile command.

**Comment by regou** [comment]
Update: 
You can try [gulp-sourcemap with {loadMaps: true}](https://github.com/floridoo/gulp-sourcemaps#load-existing-source-maps)
